#ifndef NEBUSHELL_CONSTANTS_H
#define NEBUSHELL_CONSTANTS_H

#define MAX_DIRECTORY_LENGTH 1024
#define MAX_HISTORY 1024
#define MAX_COMMAND_LENGTH 1024
#define MAX_LINES 1024
#define LINES_TO_REMOVE 100
#define MAX_LINE_LENGTH 1024
#define FULL_ALIAS_LENGTH 256
#define MAX_ARGS_LENGTH 1024
#define MAX_PATH_LENGTH 256

#endif //NEBUSHELL_CONSTANTS_H
